apiVersion: v1
kind: Pod
metadata:
  labels:
    app: omgwtfssl
  name: omgwtfssl
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: SSL_SUBJECT
      value: cloud.mosrealstroy.ru
    - name: CA_SUBJECT
      value: a.kapustin@mosrealstroy.ru
    - name: SSL_KEY
      value: /certs/mrs.key
    - name: SSL_CSR
      value: /certs/mrs.csr
    - name: SSL_CERT
      value: /certs/mrs.crt
    name: omgwtfssl
    image: paulczar/omgwtfssl
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: certs
      name: certs
  volumes:
    - name: certs
      hostPath:
        path: "/mnt/certs-pv"
