apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
    - name: http
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: proxy 
